1UPDATE
NagarajJkd/ProjectHandlingRepo pull request #3
Opened 2023-01-19 12:14 UTC by VinayVini2501

2023-01-19 12:17 UTC, NagarajJkd commented on src/test/java/CustomerModule.java
> +		System.out.println(" this is emty");
add more printing statements

2023-01-19 12:18 UTC, VinayVini2501 commented on src/test/java/CustomerModule.java
> +		System.out.println(" this is emty");
OK I ILL WRITE

2023-01-19 15:02 UTC, VinayVini2501 reviewed
ok

2023-01-20 04:17 UTC, NagarajJkd requested changes

2023-01-20 04:17 UTC, NagarajJkd commented on src/test/java/com/myNewProject/UserModule.java
> -		Repoter.log("");
accepted

2023-01-20 04:17 UTC, NagarajJkd commented on src/test/java/com/myNewProject/UserModule.java
> -	public void userLogin() {
change the class name

2023-01-20 04:18 UTC, NagarajJkd approved these changes
approved

2023-01-20 04:18 UTC, merged